<?php

$width = '530px';

?>
<div class="modal_location_popup" style="display:none">
		<div class="location_popup" id="location-popup" style="width: <?php echo $width; ?>;">	
			<button class="action-close" data-role="closeBtn" type="button">
				<em class="pe-7s-close"></em>
            </button>		
			<div class="block-popup-subscribe">
				<div class="block-popup-top">
					<div class="pop-location-title">
						<svg width="20" height="24" viewBox="0 0 20 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M19 10C19 17 10 23 10 23C10 23 1 17 1 10C1 7.61305 1.94821 5.32387 3.63604 3.63604C5.32387 1.94821 7.61305 1 10 1C12.3869 1 14.6761 1.94821 16.364 3.63604C18.0518 5.32387 19 7.61305 19 10Z" stroke="#142A75" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
							<path d="M10 13C11.6569 13 13 11.6569 13 10C13 8.34315 11.6569 7 10 7C8.34315 7 7 8.34315 7 10C7 11.6569 8.34315 13 10 13Z" stroke="#142A75" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
						</svg>
						<p id="pop-location-title__name"></p>
					</div>					
                    <div class="location-popup-content">
						<p><b><?php /* @escapeNotVerified */ echo __('Select your current location') ?>:</b><br><?php /* @escapeNotVerified */ echo __('and you can help us to improve your experience, showing availabilities and customizing your journey. If its not your location, you can change it later') ?></p> 
                    </div>					
					<div class="location-popup-form">
						<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Aventi_LocationPopup::form.phtml")->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
</div>
<div style="display:none" class="toast__container">
	<div class="toast__cell">
		<div class="toast toast--blue add-margin">
			<div class="toast__icon">
				<svg class="toast__svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" >
					<g>
						<g id="info">
							<g>
								<path  d="M10,16c1.105,0,2,0.895,2,2v8c0,1.105-0.895,2-2,2H8v4h16v-4h-1.992c-1.102,0-2-0.895-2-2L20,12H8     v4H10z"></path>
								<circle  cx="16" cy="4" r="4"></circle>
							</g>
						</g>
					</g>

				</svg>
			</div>
			<div class="toast__content">
				<p class="toast__type">¡Cuidado!</p>
				<p class="toast__message">La disponibilidad de inventario y precios son susceptibles a los cambios de ciudad</p>
			</div>
			<div class="toast__close">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.642 15.642" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 15.642 15.642">
					<path fill-rule="evenodd" d="M8.882,7.821l6.541-6.541c0.293-0.293,0.293-0.768,0-1.061  c-0.293-0.293-0.768-0.293-1.061,0L7.821,6.76L1.28,0.22c-0.293-0.293-0.768-0.293-1.061,0c-0.293,0.293-0.293,0.768,0,1.061  l6.541,6.541L0.22,14.362c-0.293,0.293-0.293,0.768,0,1.061c0.147,0.146,0.338,0.22,0.53,0.22s0.384-0.073,0.53-0.22l6.541-6.541  l6.541,6.541c0.147,0.146,0.338,0.22,0.53,0.22c0.192,0,0.384-0.073,0.53-0.22c0.293-0.293,0.293-0.768,0-1.061L8.882,7.821z"></path>
				</svg>
			</div>
		</div>
	</div>	
</div>
	