<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \MGS\InstantSearch\Block\SearchResult\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$limit = $block->getPositionLimit();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png');
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
if($settings['catalogsearch']['per_row']){
    $perrow = $settings['catalogsearch']['per_row'];
}
$colCheck = $themeHelper->convertPerRowtoCol($perrow);
$colClass = $themeHelper->convertColClass($colCheck, 'col');
?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
<?php $size = $themeHelper->getImageSize(); ?>
<?php $padding = $themeHelper->getImagePadding(); ?>
<div class="block block-title">
    <h4><?php echo __('Products') ?></h4>
    <?php if($_productCollection->count() && $_productCollection->getSize() > $limit): ?>
        <div class="view-more">
            <a href="<?php /* @escapeNotVerified */ echo $block->getResultUrl() ?>"><?php /* @escapeNotVerified */ echo $block->getViewMoreLabel() ?></a>
        </div>
    <?php endif; ?>
</div>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = $block->showShortDescription();
        $showReview = $block->showReview();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
    ?>
	<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php $iterator = 1; ?>
		<ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i=0; foreach ($_productCollection as $_product): $i++ ?>
            	<li class="item product product-item <?php echo $colClass ?> <?php echo $themeHelper->getClearClass($perrow, $i) ?>">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                            $image = 'category_page_grid';
                        ?>
                        <div class="product-in-grid-container">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
                            <?php if(!$lazyLoad): ?>
                                <?php $baseImage = $productImage ?>
                            <?php endif ?>
                            <?php // Product Image ?>
                            <div class="product-top">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo"  style="padding-bottom: <?php echo $padding; ?>;" tabindex="-1">
                                    <img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
                                </a>
                                <?php echo $themeHelper->getProductLabel($_product) ?>
                            </div>
                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h5 class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h5>
                                <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($_product->isSaleable() && $_product->isAvailable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form class="to-cart-form" data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <button type="submit"
                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                class="action tocart btn-cart-custom">
                                            <span>
                                            <svg width="20" height="22" viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <g clip-path="url(#clip0)">
                                                <path d="M14.7899 13.6799L18.4499 14.8099C18.9299 14.9399 19.3899 15.1999 19.6699 15.6099C19.9899 16.0799 20.0299 16.6799 19.9899 17.2299C19.9599 17.7799 19.8799 18.3699 19.4999 18.7999C19.4299 18.8799 19.3299 18.9399 19.2599 19.0199C19.6599 18.5699 18.9599 18.0199 18.2199 17.7799L14.4699 16.5699C13.4999 16.2699 13.0099 15.5399 13.0099 14.5899C13.0099 14.5899 12.8599 13.1199 13.7399 12.4399C13.3499 12.8899 14.0499 13.4399 14.7899 13.6799Z" fill="white"/>
                                                <path d="M14.7899 13.6802L18.4499 14.8102C18.9199 14.9402 19.3599 15.1802 19.6499 15.5802C20.0199 16.1102 20.0199 16.7702 19.9799 17.3802C19.9499 17.8702 19.8499 18.3902 19.5199 18.7802C19.4499 18.8702 19.3499 18.9302 19.2699 19.0102C19.6699 18.5602 18.9699 18.0102 18.2299 17.7702L14.4799 16.5602C13.5099 16.2602 13.0199 15.5302 13.0199 14.5802C13.0199 14.5802 12.8699 13.1102 13.7499 12.4302C13.3499 12.8902 14.0499 13.4402 14.7899 13.6802Z" fill="white"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.22 17.78C18.96 18.02 19.66 18.57 19.26 19.02C19.27 19.01 19.27 19.01 19.28 19C18.99 19.26 18.59 19.5 18.06 19.72L13 21.92V20.36C13 19.3 13.48 18.53 14.93 17.92L16.52 17.23L18.22 17.78Z" fill="white"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.22 17.78C18.96 18.02 19.66 18.57 19.26 19.02C19.27 19.01 19.27 19.01 19.28 19C18.99 19.26 18.59 19.5 18.06 19.72L13 21.92V20.36C13 19.3 13.48 18.53 14.93 17.92L16.52 17.23L18.22 17.78Z" fill="white"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M13.3301 12.9104C13.3401 12.9004 13.3401 12.8904 13.3501 12.8804C13.3501 12.8904 13.3401 12.9004 13.3301 12.9104Z" fill="white"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.67 11.5301C18.71 11.5001 18.59 11.6201 18.52 11.6801C17.9 12.2001 17.16 12.5001 16.37 12.6401C15.5 12.7901 14.59 12.7301 13.75 12.4401C13.73 12.4301 13.72 12.4801 13.68 12.5301C13.43 12.9601 14.09 13.4601 14.78 13.6901L16.48 14.2201C17.92 13.5901 19.98 12.9901 19.99 11.1001C19.99 11.1001 20 9.53009 19.99 9.54009C19.85 9.70009 19.69 9.85009 19.51 9.97009C18.82 10.4601 17.97 10.6101 17.16 10.7901C16.23 11.0001 15.37 11.3501 14.56 11.8201C14.34 11.9501 14.23 12.0201 14.02 12.1601C14.03 12.1601 16.65 12.8901 18.67 11.5301Z" fill="white"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.67 11.5301C18.71 11.5001 18.59 11.6201 18.52 11.6801C17.9 12.2001 17.16 12.5001 16.37 12.6401C15.5 12.7901 14.59 12.7301 13.75 12.4401C13.73 12.4301 13.72 12.4801 13.68 12.5301C13.43 12.9601 14.09 13.4601 14.78 13.6901L16.48 14.2201C17.92 13.5901 19.98 12.9901 19.99 11.1001C19.99 11.1001 20 9.53009 19.99 9.54009C19.85 9.70009 19.69 9.85009 19.51 9.97009C18.82 10.4601 17.97 10.6101 17.16 10.7901C16.23 11.0001 15.37 11.3501 14.56 11.8201C14.34 11.9501 14.23 12.0201 14.02 12.1601C14.03 12.1601 16.65 12.8901 18.67 11.5301Z" fill="white"/>
                                                <path d="M18.4301 5.61973L18.4101 5.55973V5.54973C18.2301 5.04973 17.7501 4.71973 17.2101 4.71973H3.26008C2.79008 4.71973 2.39008 5.01973 2.26008 5.45973L2.25008 5.46973L0.180084 16.6197C-0.209916 17.8997 0.0400839 19.2597 0.850084 20.3297C1.64008 21.3797 2.93008 21.9997 4.29008 21.9997L10.3301 21.9097C10.9201 21.9097 11.4001 21.4297 11.4001 20.8497C11.4001 20.5697 11.2901 20.2997 11.0901 20.0997C10.8901 19.8997 10.6201 19.7897 10.3301 19.7897L4.28008 19.8797C3.59008 19.8797 2.94008 19.5697 2.55008 19.0397C2.16008 18.5097 2.04008 17.8497 2.24008 17.2197L2.25008 17.1997L4.11008 6.83973H16.5501L16.8901 9.21973L17.3201 9.05973C17.6501 8.92973 17.9401 8.78973 18.1901 8.60973C18.3701 8.47973 18.5401 8.32973 18.6901 8.16973L18.8101 8.03973L18.4301 5.61973Z" fill="white"/>
                                                <path d="M15.7901 8.51997H15.7001H15.7901C15.7801 6.21997 15.7601 2.75997 13.5501 0.999968C12.5601 0.209968 11.2801 -0.110032 9.74007 0.0299682C7.68007 0.219968 6.24007 1.46997 5.45007 3.74997C4.83007 5.52997 4.79007 7.50997 4.82007 8.53997C4.83007 8.82997 4.96007 9.09997 5.18007 9.29997C5.43007 9.50997 5.76007 9.62997 6.10007 9.59997C6.73007 9.54997 7.21007 9.05997 7.20007 8.47997C7.18007 7.73997 7.20007 6.60997 7.43007 5.47997C7.84007 3.42997 8.70007 2.32997 9.98007 2.20997C10.8501 2.12997 11.5101 2.27997 12.0001 2.65997C13.3901 3.75997 13.4101 6.73997 13.4201 8.51997V8.55997C13.4201 8.83997 13.5401 9.10997 13.7501 9.30997C13.9701 9.52997 14.2901 9.64997 14.6101 9.64997H14.6301C15.2801 9.63997 15.8001 9.13997 15.8001 8.54997L15.7901 8.51997Z" fill="white"/>
                                                </g>
                                                <defs>
                                                <clipPath id="clip0">
                                                <rect width="20" height="22" fill="white"/>
                                                </clipPath>
                                                </defs>
                                            </svg>

                                            </span>
                                        </button>
                                    </form>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
            	</li>
            <?php endforeach; ?>
        </ol>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>