<?php
    /**
     * @var Aventi\ForceLogin\Block\TermsAndConditions $block
     */
    if (!$block->getAgreements()) {
        return;
    }
    /** @var \Magento\CheckoutAgreements\Model\ResourceModel\Agreement\Collection $argeementsCollection */
    $argeementsCollection = $block->getAgreements();
    $agreementMappedArray = [];
    /** @var \Magento\CheckoutAgreements\Model\Agreement $agreement */
    foreach ($argeementsCollection as $agreement) {
        if ($agreement->getIsActive()) {
            $agreementMappedArray[] = [
                'mode' => $agreement->getMode(),
                'agreementId' => $agreement->getAgreementId(),
                'checkboxText' => $agreement->getCheckboxText(),
                'content' => $agreement->getContent()
            ];
        }
    }
    $agreementJson = json_encode($agreementMappedArray);
?>
<div data-bind="scope: 'checkout-agreements-component-scope'" class="field choice mgs-gdpr-checkbox">
    <input name="login[accept_gdpr]" value="1" id="accept_gdpr" class="checkbox" type="checkbox" data-validate="{required:true}"/>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
     {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "checkout-agreements-component-scope": {
                        "component": "Magento_CheckoutAgreements/js/view/checkout-agreements",
                        "agreements": <?php /* @noEscape */ echo $agreementJson; ?>,
                        "isVisible": true
                    }
                }
            }
        }
    }
</script>
<script>
    requirejs([
        'jquery'
    ], function ($){
        $(document).on('ready', function(){

            $(document).on('click', 'button.action.login', function(){

                if(!$("#accept_gdpr").is(':checked')){
                    if($("div.mage-error.error-gdpr").length > 0){
                        $("div.mage-error.error-gdpr").css('display', 'block')
                    }else{
                        $(".checkout-agreements.fieldset").append('<div for="login[accept_gdpr]" generated="true" class="mage-error error-gdpr" id="login[accept_gdpr]-error" style="display: block;">Este es un campo obligatorio.</div>');
                    }
                }
            });

        });
    });
</script>
