<?php
$totalList = $block->getTotalList();


?>
<?php if (is_array($totalList)) : ?>
    <div class="block block-dashboard-credit">
        <div class="block-title--myac">
			<h3>
            <?= __('Portfolio Information') ?>
            </h3>
		</div>
        <div class="block-content">
            <div class="box box-information">
                <div class="box-content">
                    <?php foreach ($totalList as $key => $total) :  ?>
                        <div class="content-total">
                            <h4><?php echo __($key); ?></h4>
                            <div class="content-total__filler"></div>
                            <p><?php echo __($total); ?></p>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
