<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
<?php $swatches = $this->getSwatches(); ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $baseImageHover = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>
<?php $useSlider = $this->getUseSlider(); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $image = 'category_page_grid'; ?>
<?php $_image = 'product_thumbnail_image'; ?>

<?php
	/** Add code */
		$_aHelper = $this->helper('MGS\AjaxCart\Helper\Data');
		$animationType = $_aHelper->getConfig('ajaxcart/additional/animation_type');
	/**End add code */
?>

<?php
	$hover_effect = "";
	if ($themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect')== 1){
		$hover_effect = "disable_hover_effect";
	}
	if ($themeHelper->getStoreConfig('mpanel/catalog/disable_button_cart_hover_effect')== 1){
		$hover_effect .= "disable_button_cart_hover_effect";
	}
?>

<?php $_product = $this->getLoadProduct($this->getProductId()); ?>

<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>

<div class="product-item-info <?php echo $hover_effect ?>" data-container="product-grid">
	<div class="product-in-grid-container">
		<?php // Product Top ?>
		<div class="product-top">
			<?php // Product Image ?>
			<?php $size = $themeHelper->getImageSize($this->getRatio()); ?>
			<?php $padding = $themeHelper->getImagePadding($this->getRatio()); ?>

			<?php
				$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
				 $productImageSmall = $_imagehelper->init($_product, 'product_small_image')->resize($size['width'], $size['height'])->getUrl();
				$productThumbnail = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
				$productImageBase = $_imagehelper->init($_product, 'product_base_image')->resize($size['width'], $size['height'])->getUrl();
				$productImageHover = $_imagehelper->init($_product, $_image)->resize($size['width'], $size['height'])->getUrl();
				if(!$lazyLoad){
					$baseImage = $productImage;
					$baseImageHover = $productImageHover;
				}
			?>
			<?php if($themeHelper->getStoreConfig('mpanel/catalog/images_slides')== 1): ?>
			   <div class="owl-carousel list_gallery">
					<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
						<img src="<?php echo $productImageBase ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
					</a>
				   <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
					   <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
						<img src="<?php echo $productThumbnail ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail" data-src="<?php echo $productThumbnail ?>"/>
					   </a>
				   <?php endif;?>

				  <?php if((basename($_product->getData('small_image')) != basename($_product->getData('image'))) && (basename($_product->getData('small_image')) != basename($_product->getData('thumbnail')))): ?>
						<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
							<img src="<?php echo $productImageSmall ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail" data-src="<?php echo $productImageSmall ?>"/>
					   </a>
				   <?php endif;?>

				</div>

			<?php else:?>
			 <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">

				<img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> <?php if($useSlider): ?> owl-lazy<?php else: ?> lazy<?php endif ?><?php endif ?>"  data-src="<?php echo $productImage ?>"/>

				<?php if(basename($_product->getData('thumbnail')) !=  'no_selection'): ?>
					<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
						<img src="<?php echo $baseImageHover ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-hover-show<?php if($lazyLoad): ?> <?php if($useSlider): ?> owl-lazy<?php else: ?> lazy<?php endif ?><?php endif ?>"  data-src="<?php echo $productImageHover ?>"/>
					<?php endif ?>
				<?php endif ?>

				<div class="product-image-photo"></div>
			</a>

			<?php endif;?>


			<?php // Product Label ?>
			<?php echo $themeHelper->getProductLabel($_product) ?>

			<?php // Product Action ?>
			<ul class="actions-link">


				<?php // Wishlist  ?>
				<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
					<li>
						<button class="action towishlist"
						   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
						   data-title="<?php echo __('Add to Wish List') ?>"
						   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
						   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
						   data-action="add-to-wishlist"
						   role="button">
						   <svg width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M9.5 1L12.1265 6.59516L18 7.4979L13.75 11.8507L14.753 18L9.5 15.0952L4.247 18L5.25 11.8507L1 7.4979L6.8735 6.59516L9.5 1Z" fill="white" stroke="#333333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
						</button>
					</li>
				<?php endif; ?>

				<!-- <?php // Compare  ?>
				<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
				<?php if(!$themeSettings['catalog']['compare_button']): ?>
					<li>
						<button class="action tocompare"
						   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
						   data-title="<?php echo __('Add to Compare') ?>"
						   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
						   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
						   role="button">
							<i class="pe-7s-graph3"></i>
						</button>
					</li>
				<?php endif ?> -->
			</ul>
			<?php // QuickView  ?>

			<div class="quick-view-container hidden-sm hidden-xs">
				<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
				<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
			</div>
		</div>

		<?php // Product Detail ?>
		<div class="product details product-item-details">


			<?php // Product Qty x Unit ?>
			<!-- <h6 class="price-by-unit">
				250g...
			</h6> -->
			<?php // Product Name ?>
			<h5 class="product name product-item-name">
				<a class="product-item-link"
				title="<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"
				href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
					<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				</a>
			</h5>

			<?php // Swatches Product ?>
			<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTextSwatch($swatches)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>

			<?php // Price ?>
			<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

			<div class="field qty">
											<div class="control">
												<span class="edit-qty minus" onclick="minusQty('qty', '<?php echo $_product->getId(); ?>')" data-id="<?php echo $_product->getId(); ?>">-</span>
												<input type="number" name="qty" id="qty" maxlength="12" value="1" title="Qty" class="input-text qty" data-id="<?php echo $_product->getId(); ?>" data-validate="{&quot;required-number&quot;:true,&quot;validate-item-quantity&quot;:{&quot;minAllowed&quot;:1,&quot;maxAllowed&quot;:10000}}">
												<span class="edit-qty plus" onclick="plusQty('qty', '<?php echo $_product->getId(); ?>')" data-id="<?php echo $_product->getId(); ?>">+</span>
											</div>
										</div>

			<?php if ($themeHelper->getStoreConfig('mpanel/catalog/disable_add_to_cart') == 0 && ($themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect') == 1 || $themeHelper->getStoreConfig('mpanel/catalog/disable_button_cart_hover_effect') ==1)): ?>
				<?php if ($_product->isSaleable()): ?>
					<div>
						<?php $postParams = $block->getAddToCartPostParams($_product); ?>
						<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
							<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
							<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
							<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />

							<?php
								$has_option = 0;
								if($_product->getTypeId() == 'simple'){
									$data = $_product->getData();
									$has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
								}
							?>

							<?php if($animationType == 'cartshow' && ($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'bundle' || $_product->getTypeId() == 'grouped' || ($_product->getTypeId() == 'simple' && $has_option == 1) )): ?>
								<button class="action tocart btn-cart hover_effect" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="window.location.href = '<?php echo $_product->getProductUrl() ?>'">
									<span class="icon pe-7s-shopbag"></span>
									<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
								</button>
							<?php else: ?>
								<button class="action tocart btn-cart hover_effect" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
									<span class="icon pe-7s-shopbag"></span>
									<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
								</button>
							<?php endif; ?>
						</form>
					</div>
				<?php endif ?>
			<?php endif ?>

			<?php // Add to cart ?>
			<?php if ($themeHelper->getStoreConfig('mpanel/catalog/hover') == 'template-2' ) : ?>
				<?php if ($_product->isSaleable()): ?>
					<div class="button-minicart">
						<?php $postParams = $block->getAddToCartPostParams($_product); ?>
						<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
							<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
							<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
							<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
							<?php
								$has_option = 0;
								if($_product->getTypeId() == 'simple'){
									$data = $_product->getData();
									$has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
								}
							?>

							<?php if($animationType == 'cartshow' && ($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'bundle' || $_product->getTypeId() == 'grouped' || ($_product->getTypeId() == 'simple' && $has_option == 1) )): ?>
								<button class="action tocart btn-cart" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="window.location.href = '<?php echo $_product->getProductUrl() ?>'">
									<span class="icon pe-7s-shopbag"></span>
									<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
								</button>
							<?php else: ?>
								<button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
									<span class="icon pe-7s-shopbag"></span>
									<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
								</button>
							<?php endif; ?>
						</form>
					</div>
				<?php endif ?>
			<?php endif ?>

			<?php // Add to cart ?>
			<?php if ($themeHelper->getStoreConfig('mpanel/catalog/disable_add_to_cart')== 0 && $themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect') == 0 && $themeHelper->getStoreConfig('mpanel/catalog/disable_button_cart_hover_effect') == 0): ?>
				<?php if ($_product->isSaleable()): ?>
					<?php if ($themeHelper->getStoreConfig('mpanel/catalog/hover') != 'template-2' ) : ?>
						<div>
							<?php $postParams = $block->getAddToCartPostParams($_product); ?>
							<form data-role="tocart-form" class="to-cart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
								<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
								<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                <input type="hidden" id="addto_<?= $_product->getId(); ?>" name="qty" value="">
								<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />

								<?php
									$has_option = 0;
									if($_product->getTypeId() == 'simple'){
										$data = $_product->getData();
										$has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
									}
								?>
								<?php if($animationType == 'cartshow' && ($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'bundle' || $_product->getTypeId() == 'grouped' || ($_product->getTypeId() == 'simple' && $has_option == 1) )): ?>
									<button class="action tocart btn-cart-custom" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="window.location.href = '<?php echo $_product->getProductUrl() ?>'">
										<svg width="20" height="22" viewBox="0 0 20 22" fill="none" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" xmlns="http://www.w3.org/2000/svg">
											<path d="M4 1L1 5V19C1 19.5304 1.21071 20.0391 1.58579 20.4142C1.96086 20.7893 2.46957 21 3 21H17C17.5304 21 18.0391 20.7893 18.4142 20.4142C18.7893 20.0391 19 19.5304 19 19V5L16 1H4Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
											<path d="M1 5H19" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
											<path d="M14 9C14 10.0609 13.5786 11.0783 12.8284 11.8284C12.0783 12.5786 11.0609 13 10 13C8.93913 13 7.92172 12.5786 7.17157 11.8284C6.42143 11.0783 6 10.0609 6 9" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
										</svg>
									</button>
								<?php else: ?>
									<button class="action tocart btn-cart-custom" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
									<svg width="20" height="22" viewBox="0 0 20 22" fill="none" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" xmlns="http://www.w3.org/2000/svg">
										<path d="M4 1L1 5V19C1 19.5304 1.21071 20.0391 1.58579 20.4142C1.96086 20.7893 2.46957 21 3 21H17C17.5304 21 18.0391 20.7893 18.4142 20.4142C18.7893 20.0391 19 19.5304 19 19V5L16 1H4Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
										<path d="M1 5H19" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
										<path d="M14 9C14 10.0609 13.5786 11.0783 12.8284 11.8284C12.0783 12.5786 11.0609 13 10 13C8.93913 13 7.92172 12.5786 7.17157 11.8284C6.42143 11.0783 6 10.0609 6 9" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
									</svg>
								</button>
								<?php endif; ?>
							</form>
						</div>
					<?php endif ?>
				<?php endif ?>
			<?php endif ?>

		</div>
	</div>
</div>
<script type="text/javascript">
    function plusQty(qtyInput, id){
        require([
            'jquery'
        ], function(jQuery){
            (function($) {
                let element = $('input[id="'+qtyInput+'"][data-id="'+id+'"]');
                if(element.attr('disabled')!='disabled'){
                    qty = element.attr('value');
                    qty = parseInt(qty);
                    qty++;
                    element.val(qty);
                    $('#addto_'+id).val(qty);
                }
            })(jQuery);
        });

    }
    function minusQty(qtyInput, id){
        require([
            'jquery'
        ], function(jQuery){
            (function($) {
                let element = $('input[id="'+qtyInput+'"][data-id="'+id+'"]');
                if(element.attr('disabled')!='disabled'){
                    qty = element.attr('value');
                    qty = parseInt(qty);

                    if(qty>1){
                        qty--;
                        element.val(qty);
                        $('#addto_'+id).val(qty);
                    }
                }
            })(jQuery);
        });
    }
</script>
