<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>

<?php $logo = $block->getChildHtml('logo'); //Logo ?>

<div class="block block-customer-login">
    <div class="login-form-container">
        <div class="login-form-container__introduction">
            <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
            <div class="block-title">
                <h2 class="title" id="block-customer-login-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Welcome') ?></span></h2>
                <p><?php /* @escapeNotVerified */ echo __('You only can access to our online store as a client. With an user and a password') ?></p>
            </div>
        </div>
        <form class="form form-login login-form-container__form"
            action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
            method="post"
            id="login-form"
            data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="form-group email required">
                    <div class="form-group">
                        <label for="login[username]" class="required"><?php echo __('Email Address'); ?><em>*</em></label>
                        <div class="control">
                            <input name="login[username]" placeholder="<?php echo __('Email Address'); ?>" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                            <svg width="22" height="18" viewBox="0 0 22 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3 1H19C20.1 1 21 1.9 21 3V15C21 16.1 20.1 17 19 17H3C1.9 17 1 16.1 1 15V3C1 1.9 1.9 1 3 1Z" stroke="#333333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                <path d="M21 3L11 10L1 3" stroke="#333333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>

                        </div>	
                    </div>
                </div>
                <div class="form-group password required">
                    <div class="form-group">
                        <label for="login[username]" class="required"><?php echo __('Password'); ?><em>*</em></label>
                        <div class="control">
                            <input name="login[password]" placeholder="<?php echo __('Password'); ?>" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                            <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M14.4319 6.5L17.9319 3M19.9319 1L17.9319 3L19.9319 1ZM10.3219 10.61C10.8383 11.1195 11.2487 11.726 11.5297 12.3948C11.8106 13.0635 11.9565 13.7813 11.9589 14.5066C11.9614 15.232 11.8203 15.9507 11.5438 16.6213C11.2674 17.2919 10.861 17.9012 10.3481 18.4141C9.83515 18.9271 9.22584 19.3334 8.55522 19.6099C7.8846 19.8864 7.16591 20.0275 6.44055 20.025C5.71518 20.0226 4.99746 19.8767 4.32871 19.5958C3.65995 19.3148 3.05338 18.9043 2.54392 18.388C1.54205 17.3507 0.987677 15.9614 1.00021 14.5193C1.01274 13.0772 1.59117 11.6977 2.61091 10.678C3.63066 9.65825 5.01013 9.07982 6.45221 9.06729C7.89429 9.05476 9.2836 9.60913 10.3209 10.611L10.3219 10.61ZM10.3219 10.61L14.4319 6.5L10.3219 10.61ZM14.4319 6.5L17.4319 9.5L20.9319 6L17.9319 3L14.4319 6.5Z" stroke="#333333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </div>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <button type="submit" class="action login btn btn-primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
                    <a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="login-right-background">
        <div class="login-right-background__container">
            <div class="block-login-bck" style="background-image: url('<?php echo $block->getUrl("pub/media/main_banners/")?>alimentacion.jpg');">
                <h2>Alimentos</h2>
            </div>
            <div class="block-login-bck __blck-2">
                <h2>Café y Aromáticas</h2>
            </div>
            <div class="block-login-bck __blck-3">
                <h2>Higiene y <br>cuidado personal</h2>
            </div>
        </div>
    </div>
</div>
